/**
 * @fileoverview gRPC-Web generated client stub for sum
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: sum.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as sum_pb from './sum_pb'; // proto import: "sum.proto"


export class SumServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAdd = new grpcWeb.MethodDescriptor(
    '/sum.SumService/Add',
    grpcWeb.MethodType.UNARY,
    sum_pb.SumRequest,
    sum_pb.SumReply,
    (request: sum_pb.SumRequest) => {
      return request.serializeBinary();
    },
    sum_pb.SumReply.deserializeBinary
  );

  add(
    request: sum_pb.SumRequest,
    metadata?: grpcWeb.Metadata | null): Promise<sum_pb.SumReply>;

  add(
    request: sum_pb.SumRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: sum_pb.SumReply) => void): grpcWeb.ClientReadableStream<sum_pb.SumReply>;

  add(
    request: sum_pb.SumRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: sum_pb.SumReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sum.SumService/Add',
        request,
        metadata || {},
        this.methodDescriptorAdd,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sum.SumService/Add',
    request,
    metadata || {},
    this.methodDescriptorAdd);
  }

}

